import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="bg-gray-800 p-4">
          <div className="container mx-auto flex justify-between items-center">
            <h1 className="text-white text-xl">Student Management System</h1>
            <Link
              className="text-white bg-gray-600 hover:bg-gray-400 py-2 px-10 rounded"
              href="/"
            >
              Home
            </Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
